# Generated by Django 5.1.15 on 2026-06-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_profile_fields"),
        ("accounts", "0002_alter_user_managers_user_allow_public_reports_and_more"),
    ]

    operations = []
