# Generated by Django 5.1.15 on 2026-06-16 13:38

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_has_completed_onboarding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notification_preferences",
            field=models.JSONField(default=accounts.models._default_notification_preferences),
        ),
    ]
