# Generated by Django 5.2.15 on 2026-06-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_notification_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_method",
            field=models.CharField(default="manual", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="google_sub",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
