# Generated by Django 5.2.15 on 2026-07-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_google_auth_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sector",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
