# Generated by Django 5.1.15 on 2026-06-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_recyclingactivity_deleted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=200)),
                ("required_points", models.IntegerField(default=0)),
                ("badge_type", models.CharField(default="points", max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["required_points"],
            },
        ),
        migrations.CreateModel(
            name="PointConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("report_submitted", "Report Submitted"),
                            ("recycling_logged", "Recycling Logged"),
                            ("verification_bonus", "Verification Bonus"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("points", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["event"],
            },
        ),
    ]
