# Generated by Django 5.2.15 on 2026-06-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_seed_point_configurations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointconfiguration",
            name="event",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
