# Generated by Django 5.2.15 on 2026-06-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_point_config_open_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wastereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("resolved", "Resolved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
