# Generated by Django 5.2.15 on 2026-07-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_add_sector_to_wastereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastereport",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
