# Generated by Django 6.0.6 on 2026-07-31 23:43
# Adds AI analysis fields and fraud detection fields to WasteReport.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_add_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastereport",
            name="ai_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="ai_is_valid",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="ai_priority",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="ai_priority_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="ai_waste_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="flag_reasons",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="image_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
