# Generated by Django 5.1.15 on 2026-06-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecyclingCentre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("sector", models.CharField(max_length=100)),
                ("district", models.CharField(default="Gasabo", max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("accepted_materials", models.JSONField(default=list)),
                ("operating_hours", models.JSONField(default=dict)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
