# Generated by Django 5.2.15 on 2026-06-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycling_centres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclingcentre",
            name="close_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recyclingcentre",
            name="open_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
