# Generated by Django 5.2.15 on 2026-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycling_centres", "0002_add_open_close_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclingcentre",
            name="timezone",
            field=models.CharField(default="Africa/Kigali", max_length=60),
        ),
    ]
