# Generated by Django 5.1.15 on 2026-06-14 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NudgeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("title_en", models.CharField(max_length=200)),
                ("title_rw", models.CharField(max_length=200)),
                ("body_en", models.TextField()),
                ("body_rw", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("priority", models.IntegerField(default=10)),
                ("trigger_condition", models.JSONField(default=dict)),
                ("cooldown_hours", models.IntegerField(default=24)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["priority", "code"],
            },
        ),
        migrations.CreateModel(
            name="UserNudgeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("shown_at", models.DateTimeField(auto_now_add=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("acted_on", models.BooleanField(default=False)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="nudges.nudgerule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nudge_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-shown_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "rule", "shown_at"], name="nudges_user_user_id_e5e43f_idx"
                    )
                ],
            },
        ),
    ]
