# Generated by Django 5.2.15 on 2026-06-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("push", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushsubscription",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
