# Generated by Django 5.1.15 on 2026-06-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title_en", models.CharField(max_length=300)),
                ("title_rw", models.CharField(blank=True, max_length=300)),
                ("body_en", models.TextField()),
                ("body_rw", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="education/covers/"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("recycling", "Recycling"),
                            ("waste_reduction", "Waste Reduction"),
                            ("climate", "Climate"),
                            ("policy", "Policy"),
                            ("community", "Community"),
                        ],
                        default="recycling",
                        max_length=30,
                    ),
                ),
                ("reading_time_minutes", models.PositiveSmallIntegerField(default=3)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
