# Generated by Django 5.2.15 on 2026-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("badge_earned", "Badge Earned"),
                    ("streak_warning", "Streak Warning"),
                    ("weekly_digest", "Weekly Digest"),
                    ("community", "Community"),
                    ("admin", "Admin"),
                    ("verification", "Verification"),
                    ("rejection", "Rejection"),
                ],
                max_length=20,
            ),
        ),
    ]
